Repository ReGreenOrg/ReGreenFrontend, pull requests merged in 2025-06, with the labels that each got.

#95 Bug/인증관련
  .gitignore
  jest.config.ts
  package-lock.json
  package.json
  src/app/couple/invite/[id]/page.tsx
  src/app/couple/invited/[id]/page.tsx
  src/app/login/page.tsx
  src/features/auth/ui/LoginPage.tsx
  src/features/certification/__test__/ShareButton.test.tsx
  src/features/mypage/ui/Auth.tsx
  src/shared/lib/CoupleGuard.tsx
  src/shared/lib/http.ts
Labels: bug

#96 feat: add new icons and refactor FinishedActivityList component for i…
  public/icon/mypage/cupIcon.svg
  public/icon/mypage/leftArrow.svg
  public/icon/mypage/pictureIcon.svg
  public/icon/mypage/rightArrow.svg
  src/app/home/mypage/list/page.tsx
  src/features/certification/ui/ActivityList.tsx
  src/features/mypage/__test__/FinishedActivityList.test.tsx
  src/features/mypage/lib/useCoupleSubmitActivity.tsx
  src/features/mypage/model/mockCoupleActivities.ts
  src/features/mypage/model/type.ts
  src/features/mypage/ui/FinishedActivityList.tsx
  src/features/mypage/ui/FinishedActivityListIDetailItem.tsx
  src/features/mypage/ui/FinishedActivityListItem.tsx
  src/widgets/mypage/HeartAndCalendarCard.tsx
  src/widgets/mypage/SkeletonFinishedActivityList.tsx
Labels: feat

#101 fix: update redirect logic in LoginPage to handle user info retrieval…
  src/features/auth/ui/LoginPage.tsx
Labels: bug

#104 fix: refactor invite code handling in CoupleInvitePage and useNickNam…
  src/app/couple/invited/[id]/page.tsx
  src/entities/user/lib/useNickName.tsx
  src/entities/user/model/type.tsx
Labels: bug

#108 Bug/공유하기
  src/app/activity/[memberEcoVerificationId]/page.tsx
  src/app/loading.tsx
  src/features/certification/ui/ActivityList.tsx
  src/features/description/ui/HomedDescription.tsx
  src/features/mypage/ui/Auth.tsx
  src/widgets/LogoLoading.tsx
Labels: bug, feat

#112 Bug/공유하기
  package.json
  public/sw.js
  src/app/activity/[memberEcoVerificationId]/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers/RegisterSW.tsx
  src/features/certification/lib/postShare.ts
  src/features/certification/ui/ShareButton.tsx
  src/widgets/home/BottomNavigationBar.tsx
Labels: feat

#115 feat: add use client directive to ShareButton for client-side rendering
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#116 Bug/공유하기
  src/features/certification/lib/postShare.ts
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#122 Bug/공유하기
  src/features/certification/ui/ShareButton.tsx
  src/shared/ui/Button.tsx
Labels: bug

#124 refactor: remove unused imports and update click handling in ShareBut…
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#125 refactor: update ShareButton to use custom Button component and imple…
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#126 refactor: simplify ShareButton component by removing unused code and …
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#127 refactor: enhance ShareButton to include memberEcoVerificationId and …
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#129 refactor: enhance logging in ShareButton for better debugging during …
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#130 refactor: replace html2canvas with html-to-image for improved image g…
  package-lock.json
  package.json
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#131 refactor: comment out CaptureButton component code for future reference
  src/features/room-customizer/ui/CaptureButton.tsx
Labels: bug

#132 refactor: update ShareButton tests to include memberEcoVerificationId…
  src/features/certification/__test__/ShareButton.test.tsx
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#133 Bug/공유하기
  src/app/activity/[memberEcoVerificationId]/page.tsx
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#135 refactor: update image URL handling in Page component and add proxy r…
  src/app/activity/[memberEcoVerificationId]/page.tsx
  src/app/api/proxy/image/route.ts
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#136 refactor: enhance image loading handling in ShareButton and Page comp…
  src/app/activity/[memberEcoVerificationId]/page.tsx
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#139 refactor: integrate Toast component for better user feedback and upda…
  src/app/activity/[memberEcoVerificationId]/page.tsx
  src/features/certification/ui/ShareButton.tsx
  src/widgets/Toast.tsx
Labels: bug

#140 refactor: enhance image loading handling in ShareButton and Page comp…
  src/app/activity/[memberEcoVerificationId]/page.tsx
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#142 refactor: simplify image loading logic in ShareButton and remove unus…
  src/app/activity/[memberEcoVerificationId]/page.tsx
  src/features/certification/ui/ShareButton.tsx
Labels: bug

#146 Bug/공유하기
  package-lock.json
  package.json
  src/app/activity/[memberEcoVerificationId]/page.tsx
  src/features/certification/__test__/ShareButton.test.tsx
  src/features/certification/lib/createShareBlob.ts
Labels: bug

#151 Bug/공유하기
  package.json
  src/app/activity/[memberEcoVerificationId]/page.tsx
  src/app/api/proxy/image/route.ts
  src/features/certification/lib/createShareBlob.ts
  src/features/certification/ui/ShareButton.tsx
  src/features/splash/ui/InstallPrompt.tsx
Labels: bug

#152 refactor: remove proxy URL handling for direct image loading
  src/features/certification/lib/createShareBlob.ts
Labels: bug

#153 refactor: update image loading to use proxy API for improved handling
  src/app/api/proxy/image/route.ts
  src/features/certification/lib/createShareBlob.ts
Labels: bug

#154 Feat/우리인증내역
  src/app/activity/[memberEcoVerificationId]/page.tsx
  src/features/certification/model/useModalStore.ts
  src/features/mypage/lib/getActivityInfo.tsx
  src/features/mypage/lib/useCoupleSubmitActivity.tsx
  src/features/mypage/model/store.ts
  src/features/mypage/model/type.ts
  src/features/mypage/ui/FinishedActivityList.tsx
  src/features/mypage/ui/FinishedActivityListIDetailItem.tsx
  src/features/share/ui/BottomShareModal.tsx
  src/widgets/LogoLoading.tsx
  src/widgets/Toast.tsx
  src/widgets/mypage/SkeletonFinishedActivityList.tsx
Labels: bug, feat

#157 refactor: update activity rendering logic and enhance share functiona…
  src/features/certification/ui/ActivityList.tsx
  src/features/certification/ui/ShareButton.tsx
  src/features/mypage/model/type.ts
  src/features/mypage/ui/FinishedActivityList.tsx
  src/features/mypage/ui/FinishedActivityListIDetailItem.tsx
  src/features/mypage/ui/FinishedActivityListItem.tsx
  src/features/share/ui/BottomShareModal.tsx
  src/widgets/onboard/OnboardContainer1.tsx
Labels: bug

#158 Feat/히든미션
  src/app/page.tsx
  src/entities/user/lib/postEasterEgg.ts
  src/entities/user/ui/HeartCalendarState.tsx
  src/features/mypage/model/mockCoupleActivities.ts
  src/features/splash/ui/InstallPrompt.tsx
  src/features/splash/ui/model/store.tsx
Labels: feat

#159 Feat/히든미션
  src/entities/room/model/store.ts
  src/entities/room/model/type.tsx
  src/entities/room/ui/CategorySwiper.tsx
  src/entities/room/ui/InventoryListItem.tsx
Labels: bug

#161 refactor: simplify state management and improve error handling in Act…
  src/features/certification/ui/ActivityList.tsx
Labels: bug

#163 refactor: improve toggleFurniturePlacement logic for better readabili…
  src/features/room-customizer/model/store.tsx
Labels: feat

#165 fix: correct URL format for invite code redirection in LoginPage
  src/features/auth/ui/LoginPage.tsx
Labels: feat

#167 Bug/구매관련버그수정
  src/entities/room/ui/InventoryList.tsx
  src/entities/room/ui/InventoryListItem.tsx
  src/features/room-customizer/lib/normalizeExclusivePlacement.ts
  src/features/room-customizer/ui/Room.tsx
Labels: bug

#168 Bug/우리인증내역
  src/app/couple/invite/[id]/page.tsx
  src/app/couple/invited/page.tsx
  src/entities/user/ui/HeartCalendarState.tsx
  src/features/certification/lib/postCertification.ts
  src/features/certification/lib/postCertificationRetry.ts
  src/features/certification/model/type.ts
  src/features/certification/ui/ActivityList.tsx
  src/features/certification/ui/StatusListItem.tsx
  src/features/mypage/ui/FinishedActivityList.tsx
  src/features/room-customizer/ui/RoomSaveButton.tsx
  src/widgets/home/BottomButtons.tsx
Labels: bug

#170 Feat/아지트명
  package-lock.json
  src/app/couple/nickname/page.tsx
  src/app/globals.css
  src/app/home/page.tsx
  src/entities/user/ui/NameBoard.tsx
  src/features/couple-nickname/lib/checkIsValidNickName.ts
  src/widgets/LogoLoading.tsx
  src/widgets/home/BottomNavigationBar.tsx
Labels: feat

#173 refactor: enhance NameBoard component UI and improve input handling
  src/entities/user/ui/NameBoard.tsx
Labels: bug

#174 feat: add viewport meta tag for responsive design in RootLayout
  src/app/layout.tsx
Labels: bug

#175 feat: create Head component for viewport meta tag and integrate it in…
  src/app/head.tsx
  src/app/layout.tsx
Labels: feat

#176 refactor: remove Head component and integrate viewport meta tag direc…
  src/app/head.tsx
  src/app/layout.tsx
Labels: bug

#178 refactor: adjust WiggleBadge component styles for better responsivene…
  src/entities/user/ui/HeartCalendarState.tsx
  src/widgets/home/WiggleBadge.tsx
Labels: publish

#181 Feat/랭킹
  src/app/couple/rank/page.tsx
  src/app/globals.css
Labels: bug

#183 fix: add overflow hidden to body and SwiperBlockWrapper to prevent un…
  src/app/globals.css
  src/app/providers/SwiperBlockWrapper.tsx
Labels: bug

#184 refactor: adjust layout and image handling in onboarding components f…
  public/image/onboard/2.png
  src/app/onboard/page.tsx
  src/widgets/onboard/OnboardContainer2.tsx
Labels: bug

#187 refactor: improve name display logic in RankCard component for better…
  src/entities/rank/ui/RankCard.tsx
Labels: bug

#189 refactor: update error handling and improve login flow in LoginPage c…
  src/features/auth/model/type.ts
  src/features/auth/ui/LoginPage.tsx
Labels: bug

#191 refactor: remove unnecessary loading state and simplify rendering log…
  src/app/couple/page.tsx
Labels: bug

#194 feat: implement solo mode functionality and improve data handling…
  src/app/couple/page.tsx
  src/features/room-customizer/lib/useMyPlacedFurniture.tsx
  src/features/solo/lib/postSoloMode.ts
  src/features/solo/model/type.ts
Labels: feat

#195 refactor: update button text for solo mode in CoupleCheckPage component
  src/app/couple/page.tsx
Labels: feat

#200 [DOCS] coderabbit.yaml 추가 및 설정
  .coderabbit.yaml
Labels: documentation

#203 [FIX] improve error handling for Kakao login failure
  src/features/auth/ui/LoginPage.tsx
Labels: bug

#209 [FIX] manifest관련 경로 수정
  src/app/layout.tsx
  src/entities/rank/ui/RankList.tsx
Labels: bug

#216 [FIX] 랭킹 페이지 스크롤 문제 해결
  src/app/couple/rank/page.tsx
  src/entities/rank/ui/RankList.tsx
Labels: bug
